### ISSUE TITLE
Failed to communicate with localhost when lux is connected

### ISSUE THREAD

**Issue by saeedesmaeili** [igoogolx/lux#1]
Hi there,
When I'm trying to ping the IPv6 of localhost "::1" I get the below error.

![image](https://user-images.githubusercontent.com/7094672/206569808-6c275032-750a-4984-8ae7-28cf2f8d26e4.png)

**Comment by saeedesmaeili** [comment]
If you have the same issue in windows you can set "IPv4 Over IPv6", check the below link.
Works fine for me.
https://kb.firedaemon.com/support/solutions/articles/4000160803-prioritising-ipv4-over-ipv6-on-windows-10-and-11

**Comment by igoogolx** [comment]
Actually, IPv6 is not supported in lux. In other words, IPv6 is untested. And when lux is connected, it will block all IPv6 traffic. Think that's the reason.

**Comment by saeedesmaeili** [comment]
That seems right, after I configured "IPv4 Over IPv6" everything works fine. 
Topic closed.
