### ISSUE TITLE
无法正常使用沉浸式翻译插件里的谷歌翻译功能

### ISSUE THREAD

**Issue by zhl111** [igoogolx/lux#13]
几种代理模式都试过，似乎都不能正常使用。

另外，能增加自动选择最优代理地址的功能吗？

**Comment by igoogolx** [comment]
在 Setting 中可以开启 Auto Mode，自动选择代理

**Comment by igoogolx** [comment]
请问除了谷歌翻译，其他网站访问正常吗，可以在 Log 搜索谷歌翻译的域名，来检查 dns 是否正常解析。

**Comment by igoogolx** [comment]
clash 和 lux 不能同时开启。Lux 在退出之后会还原系统的所有更改，所以卸载重装 lux 不一定能解决问题。我推测是 clash 没有正常退出，导致系统某些设置没有被还原，建议重新开启 clash，然后正常退出 clash，确保 clash 还原系统配置，然后再开启 clash。

**Comment by igoogolx** [comment]
对你的网络造成的影响，十分抱歉，希望能及时同步进度，我会尽可能提供支持。
