### ISSUE TITLE
Windows Trojan Wacatac

### ISSUE THREAD

**Issue by tranghaviet** [igoogolx/lux#14]
Windows detect lux-core as a Trojan:
file: C:\Program Files\lux\data\flutter_assets\assets\bin\lux-core.exe

Trojan Name: Win32/Wacatac.B!ml

![image](https://github.com/igoogolx/lux/assets/23404016/8d8d7c44-d9c6-4a82-9f48-eb57b62bbab8)

**Comment by igoogolx** [comment]
It seems a false detection. [See this](https://betterprogramming.pub/a-big-problem-in-go-that-no-one-talks-about-328cc3e71378) for more. Anyway, lux-core is open sourced and you can find the code in [itun2socks](https://github.com/igoogolx/itun2socks). And its releases are built by github action. So I think you can ignore that or review the code and build it on you own.
