### ISSUE TITLE
DNS header id issue

### ISSUE THREAD

**Issue by PVMChannel** [igoogolx/lux#16]
This is a big issue, and i won't/can't use lux (for my purposes) before it gets patched, so please be quick with it.

When you use the command `dig` which comes with bind9 and is used to get DNS queries and you try to get any DNS record with it (when lux is turned on with tun mode) using `dig google.com` it works as intended but, if you do it again it will say 

`;; Warning: ID mismatch: expected ID 19583, got 3021`

The value that says 3021 is the same id as the id of first DNS request, which is incorrect and in my case, windows thinks that this is something trying to be malicious so it blocks the DNS. The ids will change randomly in your case but the second id will always be same as the id of the first message

I know that this is an issue of lux beacuse it doesn't happen when its turned off, also when i turn off and on lux it fixes but only for one query as stated above

**Comment by PVMChannel** [comment]
I just realized that the issue could be on my proxy software but that's unlikely.

**Comment by igoogolx** [comment]
It is because of the DNS cache in Lux and will be fixed in the next version.

**Comment by igoogolx** [comment]
[v0.13.0](https://github.com/igoogolx/lux/releases/tag/v0.13.0) fixed this. You can disable the DNS cache now.

![image](https://github.com/igoogolx/lux/assets/27353191/8cf0917f-15bf-490a-8c61-1402a99838e2)

**Comment by PVMChannel** [comment]
It's fixed now, thank you.
