### ISSUE TITLE
Portable Releases?

### ISSUE THREAD

**Issue by Sxderp** [igoogolx/lux#17]
It looks like portable releases are no longer being shipped. Is there a reason for this? I've found that if I extract the setup.exe and copy the lux_core.exe from within the `assets` folder I can use it as a standalone proxy client. Can this be shipped separately?

---

Aside and somewhat unrelated.. Please ignore, or spin off a new issue. I wasn't able to get the "full client (?)" open. When installing there is some executable that is installed and when run it creates a tray icon. However, I can't do anything with this tray icon. Running the lux_core.exe separately allows me to connect to the web-interface I used back in version ~2.7 (I didn't realize so much development has been happening). I'm happy with the command line invocation and don't have any interest in debugging why I couldn't open this "Dashboard".

**Comment by igoogolx** [comment]
1. Sorry for the confusion. The portable version still exists. You can download it from [itun2socks](https://github.com/igoogolx/itun2socks) which is the lux_core.
2. Lux is [FGRT](https://github.com/igoogolx/lux?tab=readme-ov-file#architecture) architecture now but 0.2.7 is developed by electron. You can right-click the tray and open the dashboard.
