### ISSUE TITLE
Localhost or 127.0.0.1 can't be used as proxy server (???)

### ISSUE THREAD

**Issue by Sxderp** [igoogolx/lux#18]
I setup a localhost socks proxy via SSH.

SSH -D 8888 remote.server

I can configure lux to use socks5 on localhost:8888.
I turn on the proxy.
It works (although, I have encountered an odd glitch or two that I haven't narrowed down yet).
I try to turn it off.
I receive the "Localhost or 127.0.0.1 can't be used as proxy server" message and the proxy does not turn off.

There are two issues here.
1. The message appears at the wrong time (turn off rather than turn on).
2. Why does this exist? It's new between 0.2.7 and 0.13.0. I don't think there's any technical reason to prohibit localhost/127.0.0.1 as it works just fine. You just can't turn it off due to the message.

**Comment by igoogolx** [comment]
Point 1 is a bug. See #4 for point 2. Anyway, since 0.2.7, many things changed. Maybe, #4 is not an issue anymore. I will try to fix it.

**Comment by igoogolx** [comment]
[v0.13.1](https://github.com/igoogolx/lux/releases/tag/v0.13.1) has fixed point 1.

**Attention**: If your server is localhost or 127.0.0.1, you must ignore the remote server manually. Here the point is lux will proxy all traffic. Normally the server is the real server, lux will do that automatically. But in this condition, lux didn't know the real server. If you don't set that, there may be a dead loop and lux can't work as expected.

<img width="1265" alt="image" src="https://github.com/igoogolx/lux/assets/27353191/ce03d55a-5492-4f4c-9db3-cb730daa263b">
