### ISSUE TITLE
app support

### ISSUE THREAD

**Issue by gvmxo** [igoogolx/lux#19]
hello sir
first of all i wanna thank you for this awesome application
second of all i wanna request a feature 
app support so you can exclude an app or include to go through proxy or be direct connection
thanks a lot

**Comment by igoogolx** [comment]
That's an easy-to-implement feature. But it may cause performance issues. It's better to make it an optional feature. It will be implemented in the next version.

**Comment by gvmxo** [comment]
thanks a lot!
You're awesome !!
