### ISSUE TITLE
ProcessException: Operation not permitted on macOS

### ISSUE THREAD

**Issue by myway7** [igoogolx/lux#36]

**Comment by myway7** [comment]
ProcessException: Operation not permitted on macOS

**Comment by igoogolx** [comment]
Hi, can you provide the version and architecture of the operating system? Did this popup appear the first time you opened Lux?

<img width="264" alt="image" src="https://github.com/user-attachments/assets/351ccac4-1d04-460a-a3f7-a426b401e38d">

**Comment by myway7** [comment]
Yes, I encountered this interface when I ran it for the first time. I have already verified that I have obtained the necessary permissions in the terminal. The only difference is that this binary executable file was compiled by myself. I don't understand why the packaged version cannot be executed while the debugging version works fine.

**Comment by myway7** [comment]
Intel
macos 14.5

**Comment by igoogolx** [comment]
Did you refer to this [doc](https://igoogolx.github.io/lux-docs/docs/getting-started/development#build) to build it? And you can check the [workflow](https://github.com/igoogolx/lux/actions/runs/10793176870/workflow) to see how it is built in github action.

**Comment by myway7** [comment]
Are you able to execute the code you compiled on your local machine?

**Comment by igoogolx** [comment]
Yes, it works on my local machine that is mac silicon os 15.0.
