### ISSUE TITLE
Use localhost as proxy server address

### ISSUE THREAD

**Issue by SADR4** [igoogolx/lux#4]
Hi
I'm using tor on WSL and wanna proxy it on whole OS, so I need to set 127.0.0.1 as server ip in lux, but lux doesn't let and alert for "true proxy server".
What's the true proxy server, and how can I use loopback IP as server address?

**Comment by igoogolx** [comment]
Sorry for the late reply. In your scenario, True proxy server is the address of your Tor server, which you need to fill in on the settings page. The proxy chain is as follows:

> lux -> localhost -> wsl -> tor server address (true proxy server)



However, using localhost as a server still lacks sufficient testing. Currently, it is not recommended to do so.

**Comment by igoogolx** [comment]
This issue will remain open until using localhost as a server becomes a stable feature.

**Comment by gvmxo** [comment]
i think you can easily solve this via making a rule for 127.0.0.1 to be direct not proxy
i am using with v2rayn with no problem
