### ISSUE TITLE
Ignored Domains / IPs

### ISSUE THREAD

**Issue by Sxderp** [igoogolx/lux#5]
Unless I'm missing it, there seems to be no settings for "ignored domains" or "ignored ips". Sometimes I need to use the proxy for outbound connections but there are things on my local network that I would still like access.

**Comment by igoogolx** [comment]
Sorry for the late reply. You can add [rules](https://igoogolx.github.io/lux-docs/docs/configuration/porxyRule/) in [v0.13.0](https://github.com/igoogolx/lux/releases/tag/v0.13.0) to ignore domains or ips.

<img width="1251" alt="image" src="https://github.com/igoogolx/lux/assets/27353191/73514c44-b1a8-4ff1-85df-128d4a5c2228">
